[JS] Add changes from Ivan 060924
rasnaut/GitHubStudyRepo pull request #71
Opened 2024-09-06 12:43 UTC by NatLi-zp

-make change

2024-09-06 12:54 UTC, rasnaut requested changes
Please, make changes according comments

2024-09-06 12:54 UTC, rasnaut commented on script.js
> +console.log("New message from Ivan 060924")
Please, change data according format DD.MM.YYYY

2024-09-06 12:57 UTC, rasnaut approved these changes

2024-09-07 07:44 UTC, merged

2024-09-07 07:44 UTC, Ant0nSB commented
Ok